name: goat end 2 end functional tests
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "API Security tests"

env:
  PYNT_ID: ${{ secrets.YOURPYNTID }}

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: get goat funtional tests 
      run: | 
        curl https://raw.githubusercontent.com/pynt-io/pynt/main/goat_functional_tests/goat_functional_test.py -o goat_e2e.py 
    - name: Run goat functional tests
      run: |
        python3 -m pip install pytest
        pytest goat_e2e.py
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli 
    - name: run pynt on the funcional tests 
      run: | 
        pynt command --cmd "pytest goat_e2e.py" --return-error=errors-only
        
